import { Metadata } from "next";
import "./globals.css";
import App from './components/App';
import { StoreProvider } from '@/redux/StoreProvider';
import { ClerkProvider } from '@clerk/nextjs';
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "HG-Template-0-Website",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <StoreProvider>
            <App>
              <Header/>
              {children}
              <Footer/>
              </App>
          </StoreProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
