import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import App from "./components/App";
import { StoreProvider } from "../redux/StoreProvider";

// import dynamic from "next/dynamic";
// import {
//   // ClerkProvider,
//   SignInButton,
//   SignedIn,
//   SignedOut,
//   UserButton
// } from '@clerk/nextjs'

// const ClerkProvider = dynamic(() =>
//   import("@clerk/nextjs").then(mod => mod.ClerkProvider),
//   { ssr: false }
// );

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ClerkProvider> */}
          <StoreProvider>
            <App>
              {children}
              {/* <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn> */}
            </App>
          </StoreProvider>
          <Footer />
        {/* </ClerkProvider> */}
      </body>
    </html>
  );
}
